package com.mada.quran_app.domain.repository

import com.mada.quran_app.data.model.SurahEntity
import javax.inject.Inject

class SurahRepositoryImpl @Inject constructor() : SurahRepository {
    override fun getSurahs(): List<SurahEntity> {
        return listOf(
            SurahEntity("الفاتحة", 1, 7),
            SurahEntity("البقرة", 2, 286),
            SurahEntity("آل عمران", 3, 200),
            SurahEntity("النساء", 4, 176),
            SurahEntity("المائدة", 5, 120),
            SurahEntity("الأنعام", 6, 165),
            SurahEntity("الأعراف", 7, 206),
            SurahEntity("الأنفال", 8, 75),
            SurahEntity("التوبة", 9, 129),
            SurahEntity("يونس", 10, 109),
            SurahEntity("هود", 11, 123),
            SurahEntity("يوسف", 12, 111),
            SurahEntity("الرعد", 13, 43),
            SurahEntity("إبراهيم", 14, 52),
            SurahEntity("الحجر", 15, 99),
            SurahEntity("النحل", 16, 128),
            SurahEntity("الإسراء", 17, 111),
            SurahEntity("الكهف", 18, 110),
            SurahEntity("مريم", 19, 98),
            SurahEntity("طه", 20, 135),
            SurahEntity("الأنبياء", 21, 112),
            SurahEntity("الحج", 22, 78),
            SurahEntity("المؤمنون", 23, 118),
            SurahEntity("النور", 24, 64),
            SurahEntity("الفرقان", 25, 77),
            SurahEntity("الشعراء", 26, 227),
            SurahEntity("النمل", 27, 93),
            SurahEntity("القصص", 28, 88),
            SurahEntity("العنكبوت", 29, 69),
            SurahEntity("الروم", 30, 60),
            SurahEntity("لقمان", 31, 34),
            SurahEntity("السجدة", 32, 30),
            SurahEntity("الأحزاب", 33, 73),
            SurahEntity("سبأ", 34, 54),
            SurahEntity("فاطر", 35, 45),
            SurahEntity("يس", 36, 83),
            SurahEntity("الصافات", 37, 182),
            SurahEntity("ص", 38, 88),
            SurahEntity("الزمر", 39, 75),
            SurahEntity("غافر", 40, 85),
            SurahEntity("فصلت", 41, 54),
            SurahEntity("الشورى", 42, 53),
            SurahEntity("الزخرف", 43, 89),
            SurahEntity("الدخان", 44, 59),
            SurahEntity("الجاثية", 45, 37),
            SurahEntity("الأحقاف", 46, 35),
            SurahEntity("محمد", 47, 38),
            SurahEntity("الفتح", 48, 29),
            SurahEntity("الحجرات", 49, 18),
            SurahEntity("ق", 50, 45),
            SurahEntity("الذاريات", 51, 60),
            SurahEntity("الطور", 52, 49),
            SurahEntity("النجم", 53, 62),
            SurahEntity("القمر", 54, 55),
            SurahEntity("الرحمن", 55, 78),
            SurahEntity("الواقعة", 56, 96),
            SurahEntity("الحديد", 57, 29),
            SurahEntity("المجادلة", 58, 22),
            SurahEntity("الحشر", 59, 24),
            SurahEntity("الممتحنة", 60, 13),
            SurahEntity("الصف", 61, 14),
            SurahEntity("الجمعة", 62, 11),
            SurahEntity("المنافقون", 63, 11),
            SurahEntity("التغابن", 64, 18),
            SurahEntity("الطلاق", 65, 12),
            SurahEntity("التحريم", 66, 12),
            SurahEntity("الملك", 67, 30),
            SurahEntity("القلم", 68, 52),
            SurahEntity("الحاقة", 69, 52),
            SurahEntity("المعارج", 70, 44),
            SurahEntity("نوح", 71, 28),
            SurahEntity("الجن", 72, 28),
            SurahEntity("المزمل", 73, 20),
            SurahEntity("المدثر", 74, 56),
            SurahEntity("القيامة", 75, 40),
            SurahEntity("الإنسان", 76, 31),
            SurahEntity("المرسلات", 77, 50),
            SurahEntity("النبأ", 78, 40),
            SurahEntity("النازعات", 79, 46),
            SurahEntity("عبس", 80, 42),
            SurahEntity("التكوير", 81, 29),
            SurahEntity("الإنفطار", 82, 19),
            SurahEntity("المطففين", 83, 36),
            SurahEntity("الإنشقاق", 84, 25),
            SurahEntity("البروج", 85, 22),
            SurahEntity("الطارق", 86, 17),
            SurahEntity("الأعلى", 87, 19),
            SurahEntity("الغاشية", 88, 26),
            SurahEntity("الفجر", 89, 30),
            SurahEntity("البلد", 90, 20),
            SurahEntity("الشمس", 91, 15),
            SurahEntity("الليل", 92, 21),
            SurahEntity("الضحى", 93, 11),
            SurahEntity("الشرح", 94, 8),
            SurahEntity("التين", 95, 8),
            SurahEntity("العلق", 96, 19),
            SurahEntity("القدر", 97, 5),
            SurahEntity("البينة", 98, 8),
            SurahEntity("الزلزلة", 99, 8),
            SurahEntity("العاديات", 100, 11),
            SurahEntity("القارعة", 101, 11),
            SurahEntity("التكاثر", 102, 8),
            SurahEntity("العصر", 103, 3),
            SurahEntity("الهمزة", 104, 9),
            SurahEntity("الفيل", 105, 5),
            SurahEntity("قريش", 106, 4),
            SurahEntity("الماعون", 107, 7),
            SurahEntity("الكوثر", 108, 3),
            SurahEntity("الكافرون", 109, 6),
            SurahEntity("النصر", 110, 3),
            SurahEntity("المسد", 111, 5),
            SurahEntity("الإخلاص", 112, 4),
            SurahEntity("الفلق", 113, 5),
            SurahEntity("الناس", 114, 6)
        )

    }
}